apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-coordinator
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-coordinator
  template:
    metadata:
      labels:
        app: job-coordinator
    spec:
      containers:
        - name: job-coordinator
          image: localhost:5001/job-coordinator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq.data.svc.cluster.local:5672/
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
