apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    name: auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
